apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-arm-pv-volume
  labels:
    type: local
spec:
  storageClassName: gitlab-arm-pv-storage
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
