apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-arm-redis-m-pv-claim
spec:
  storageClassName: gitlab-arm-redis-m-pv-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 6Gi

########### Enable it after connecting to shared storage ###########
#---
#
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: gitlab-arm-redis-r-pv-claim0
#spec:
#  storageClassName: gitlab-arm-redis-r-pv-storage
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 6Gi
#
#---
#
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: gitlab-arm-redis-r-pv-claim1
#spec:
#  storageClassName: gitlab-arm-redis-r-pv-storage
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 6Gi
#
#---
#
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: gitlab-arm-redis-r-pv-claim2
#spec:
#  storageClassName: gitlab-arm-redis-r-pv-storage
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 6Gi
