# Use an official Python runtime as a parent image
FROM python:3.8

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Make port 80 available to the world outside this container
EXPOSE 80

# Set environment variable to disable buffering
ENV PYTHONUNBUFFERED 1

# Run the trading script with arguments passed during the Docker run
CMD ["python", "matic.py"]
